name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python=0.15.10
  - python=3.11
  - ipywidgets
  - traitlets
  - pip:
    - ipyopenlayers
